# Generated by Django 5.2.3 on 2025-08-11 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ref',
        ),
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='V0001',
        ),
        migrations.AlterModelTable(
            name='member',
            table='V0002',
        ),
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default='78QBsMsJ4PK5d7V0mlppwozjXZCIE-PY59xGb9mch7s=', max_length=32)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'db_table': 'S0001',
            },
        ),
    ]
