# Generated by Django 5.2.3 on 2025-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0002_remove_member_ref_member_code_alter_company_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='n3Q4Jwf-KVm01t3JYzk3VhHY1SbZqtvhDGaeC0D3JF8=', max_length=32),
        ),
    ]
