# Generated by Django 5.2.3 on 2025-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0003_alter_appsession_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='v-E4PBeSpPm9HExCKEwv9oJC5Af7TUKb6XtX6EdU8jk=', max_length=32),
        ),
        migrations.AlterModelTable(
            name='appsession',
            table='appSession',
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
