# Generated by Django 5.2.3 on 2025-08-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0004_alter_appsession_secret_alter_appsession_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='he0VvCfwaBmtRSbYGygZRZV5HWw_7dj4mbuym-DBtMw=', max_length=32),
        ),
    ]
