# Generated by Django 5.2.3 on 2025-08-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0005_alter_appsession_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('optionList', models.CharField(max_length=30)),
                ('optionRecord', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'appEntity',
            },
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='NLzbhIttdXF-qjE-3w3HomaAxaWs6CINobZWTfn9jOg=', max_length=32),
        ),
        migrations.CreateModel(
            name='AppEntityField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('order', models.CharField(choices=[('', 'Sin Orden'), ('+', 'Ascendente'), ('-', 'Descendente')], default='', max_length=1)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.appentity')),
            ],
            options={
                'db_table': 'appEntityField',
            },
        ),
    ]
