# Generated by Django 5.2.3 on 2025-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0006_appentity_alter_appsession_secret_appentityfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appentityfield',
            name='order',
            field=models.CharField(blank=True, choices=[('', 'Sin Orden'), ('+', 'Ascendente'), ('-', 'Descendente')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='dDPrG0i52bc5H8rBtxMQ4586ZftqQFnFqlvBF7fDwi0=', max_length=32),
        ),
    ]
