# Generated by Django 5.2.3 on 2025-08-28 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0007_alter_appentityfield_order_alter_appsession_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='mfxU4vccbOblvBNMZcC3BlRLhPPPLcbp8gNJLNpybCA=', max_length=32),
        ),
    ]
