# Generated by Django 5.2.3 on 2025-09-03 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0008_member_user_alter_appsession_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('icon', models.CharField(max_length=30)),
                ('option', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'appMenuItem',
            },
        ),
        migrations.AddField(
            model_name='appentity',
            name='app',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appentityfield',
            name='order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='Xx9REfqJzCQHfjU-2VI7V4DZIGBNPMNSqy8msQoLBmw=', max_length=32),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='AppMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child', to='myprivateapp.appmenuitem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='myprivateapp.appmenuitem')),
            ],
            options={
                'db_table': 'appMenuLink',
            },
        ),
    ]
