# Generated by Django 5.2.3 on 2025-09-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0010_alter_appsession_secret_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='5zbDt3klFZFlIyf64WwVGbA7jjTsKKmndMCeDIpVyxg=', max_length=32),
        ),
    ]
