# Generated by Django 5.2.3 on 2025-09-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0011_alter_appsession_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmenulink',
            name='child',
        ),
        migrations.RemoveField(
            model_name='appmenulink',
            name='parent',
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='IlN-9JcIem5UoT5jLQvCUoIuVMONODq8dTKVqtQGSEc=', max_length=32),
        ),
 
        migrations.DeleteModel(
            name='AppMenuItem',
        ),
        migrations.DeleteModel(
            name='AppMenuLink',
        ),
    ]
