# Generated by Django 5.2.3 on 2025-09-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0012_remove_appmenulink_child_remove_appmenulink_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='vEt4eSbSHonsu75sd1gaAW5wcigj85D9x1_2c9vZ1Oo=', max_length=32),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company')),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company')),
            ],
            options={
                'db_table': 'icon',
            },
        ),
        migrations.CreateModel(
            name='AppMenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('option', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.icon')),
            ],
            options={
                'db_table': 'appMenuItem',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company')),
            ],
            options={
                'db_table': 'letter',
            },
        ),
    ]
