# Generated by Django 5.2.3 on 2025-09-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0013_alter_appsession_secret_color_icon_appmenuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='euRAuotmm4ZednW5dcKV6optR4EXE7XvkS2Jla5Oahw=', max_length=32),
        ),
        migrations.DeleteModel(
            name='AppMenuItem',
        ),
    ]
