# Generated by Django 5.2.3 on 2025-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0014_alter_appsession_secret_delete_appmenuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='6TT0kC6CEH0QDuM3kG_G0rNpp1Nlkj8qfGipdvPRwT0=', max_length=32),
        ),
    ]
