# Generated by Django 5.2.3 on 2025-09-04 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0015_alter_appsession_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='eirZYfBlPHu09bC1HHdrq1fgUdGmj0AV2yuWW5HLRSo=', max_length=32),
        ),
        migrations.CreateModel(
            name='AppMenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('option', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.icon')),
            ],
            options={
                'db_table': 'appMenuItem',
            },
        ),
    ]
