# Generated by Django 5.2.3 on 2025-09-04 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0016_alter_appsession_secret_appmenuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmenuitem',
            name='option',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='D9clPVUZvYpq2h48LnX0MdraLxf7ibuWgNs0qVhzkp0=', max_length=32),
        ),
        migrations.CreateModel(
            name='AppMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child', to='myprivateapp.appmenuitem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='myprivateapp.appmenuitem')),
            ],
            options={
                'db_table': 'appMenuLink',
            },
        ),
    ]
