# Generated by Django 5.2.3 on 2025-09-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0017_alter_appmenuitem_option_alter_appsession_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='Oih--sz1_QhDVkS7BHX-odol7X7VNBQbZlpuWF9V724=', max_length=32),
        ),
    ]
