# Generated by Django 5.2.3 on 2025-09-05 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0018_appsession_company_alter_appsession_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appsession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprivateapp.company'),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='Tw4e3SWHKLDXFLnR0b-ZXu6vrfUYFgkcN5BP6VCNd9g=', max_length=32),
        ),
    ]
