# Generated by Django 5.2.3 on 2025-09-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0019_appsession_user_alter_appsession_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsession',
            name='user',
        ),
        migrations.AddField(
            model_name='appsession',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprivateapp.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(default='Y1tLobn9QaiZYvRDPg3qC0_l5GexE-pEST9ny_X4LAc=', max_length=32),
        ),
    ]
