# Generated by Django 5.2.3 on 2025-09-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0020_remove_appsession_user_appsession_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appentity',
            name='optionList',
        ),
        migrations.RemoveField(
            model_name='appentity',
            name='optionRecord',
        ),
        migrations.RemoveField(
            model_name='appsession',
            name='company',
        ),
        migrations.AddField(
            model_name='appmenulink',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='secret',
            field=models.CharField(max_length=44),
        ),
        migrations.CreateModel(
            name='AppEntityOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('view', 'Consultar'), ('add', 'Añadir'), ('change', 'Modificar'), ('delete', 'Suprimir'), ('export', 'Exportar'), ('exec', 'Ejecutar')], default='view', max_length=10)),
                ('option', models.CharField(max_length=60, unique=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.appentity')),
            ],
            options={
                'db_table': 'appEntityOption',
            },
        ),
        migrations.AlterField(
            model_name='appmenuitem',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.appentityoption'),
        ),
    ]
