# Generated by Django 5.2.3 on 2025-09-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0021_remove_appentity_optionlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmenuitem',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.appentityoption'),
        ),
    ]
