# Generated by Django 5.2.3 on 2025-09-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0022_alter_appmenuitem_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppMenuLink',
            new_name='AppMenuTree',
        ),
        migrations.AlterField(
            model_name='appmenuitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.appentityoption'),
        ),
        migrations.AlterModelTable(
            name='appmenutree',
            table='appMenuTree',
        ),
    ]
