# Generated by Django 5.2.3 on 2025-09-22 21:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0023_rename_appmenulink_appmenutree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='value',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
