# Generated by Django 5.2.3 on 2025-09-23 14:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0024_alter_color_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='value',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['company', 'name'], name='color_company_2af220_idx'),
        ),
    ]
