# Generated by Django 5.2.3 on 2025-09-25 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0025_alter_color_value_alter_color_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='icon',
            name='modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='letter',
            name='modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='icon',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='letter',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='icon',
            index=models.Index(fields=['company', 'name'], name='icon_company_6b5185_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['company', 'name'], name='letter_company_369ceb_idx'),
        ),
    ]
