# Generated by Django 5.2.3 on 2025-09-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0026_color_modification_icon_modification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='modification',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
