# Generated by Django 5.2.3 on 2025-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0027_alter_color_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
