# Generated by Django 5.2.3 on 2025-09-25 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0028_alter_color_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
