# Generated by Django 5.2.3 on 2025-09-25 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0029_alter_color_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='modification',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
