# Generated by Django 5.2.3 on 2025-09-27 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0030_alter_color_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='modification',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
