# Generated by Django 5.2.3 on 2025-08-11 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0003_alter_appsession_secret'),
        ('mypublicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='status',
            field=models.CharField(choices=[('0', 'Publicado'), ('1', 'Diseño'), ('2', 'Bloqueado')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='site',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company'),
        ),
        migrations.AlterModelTable(
            name='section',
            table='B0002',
        ),
        migrations.AlterModelTable(
            name='site',
            table='B0001',
        ),
    ]
