# Generated by Django 5.2.3 on 2025-08-21 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypublicapp', '0002_section_description_section_order_section_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'contentType',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='icon',
            field=models.FilePathField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.FilePathField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='site',
            table='site',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('resume', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('0', 'Publicado'), ('1', 'Diseño'), ('2', 'Bloqueado')], default='1', max_length=1)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mypublicapp.contenttype')),
            ],
            options={
                'db_table': 'content',
            },
        ),
    ]
