# Generated by Django 5.2.3 on 2025-08-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypublicapp', '0003_contenttype_site_icon_site_logo_alter_section_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
