# Generated by Django 5.2.3 on 2025-08-24 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypublicapp', '0004_alter_site_icon_alter_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='backgroundColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backgroundColor', to='mypublicapp.color'),
        ),
        migrations.AddField(
            model_name='site',
            name='footerColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='footerColor', to='mypublicapp.color'),
        ),
        migrations.AddField(
            model_name='site',
            name='headerColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headerColor', to='mypublicapp.color'),
        ),
        migrations.AddField(
            model_name='site',
            name='navbarColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='navbarColor', to='mypublicapp.color'),
        ),
    ]
