# Generated by Django 5.2.3 on 2025-08-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0007_alter_appentityfield_order_alter_appsession_secret'),
        ('mypublicapp', '0005_color_site_backgroundcolor_site_footercolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company'),
        ),
        migrations.AddField(
            model_name='content',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mypublicapp.site'),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mypublicapp.site'),
        ),
    ]
