# Generated by Django 5.2.3 on 2025-09-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0011_alter_appsession_secret'),
        ('mypublicapp', '0006_color_company_content_site_contenttype_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company'),
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company')),
            ],
            options={
                'db_table': 'icon',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.company')),
            ],
            options={
                'db_table': 'letter',
            },
        ),
    ]
