# Generated by Django 5.2.3 on 2025-09-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0023_rename_appmenulink_appmenutree_and_more'),
        ('mypublicapp', '0007_alter_color_company_icon_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='headerColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headerColor', to='myprivateapp.color'),
        ),
        migrations.AlterField(
            model_name='site',
            name='navbarColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='navbarColor', to='myprivateapp.color'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footerColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='footerColor', to='myprivateapp.color'),
        ),
        migrations.AlterField(
            model_name='site',
            name='backgroundColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backgroundColor', to='myprivateapp.color'),
        ),
        migrations.RemoveField(
            model_name='icon',
            name='company',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='company',
        ),
        migrations.AddField(
            model_name='site',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.appmenuitem'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
