# Generated by Django 5.2.3 on 2025-09-27 01:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprivateapp', '0031_alter_color_modification'),
        ('mypublicapp', '0008_alter_site_headercolor_alter_site_navbarcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('tooltip', models.CharField(blank=True, max_length=60, null=True)),
                ('link', models.CharField(blank=True, max_length=60, null=True)),
                ('modification', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'social',
            },
        ),
        migrations.RemoveField(
            model_name='site',
            name='headerColor',
        ),
        migrations.AddField(
            model_name='contenttype',
            name='modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='section',
            name='modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='site',
            name='modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='site',
            name='windowColor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='windowColor', to='myprivateapp.color'),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('site', 'name')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['site', 'name'], name='section_site_id_3f8d01_idx'),
        ),
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprivateapp.icon'),
        ),
        migrations.AddField(
            model_name='social',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mypublicapp.site'),
        ),
        migrations.AddIndex(
            model_name='social',
            index=models.Index(fields=['site', 'name'], name='social_site_id_a64753_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('site', 'name')},
        ),
    ]
