# Generated by Django 5.2.3 on 2025-10-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        ('mypublicapp', '0009_social_remove_site_headercolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myapp.company'),
        ),
    ]
