# Generated by Django 5.2.3 on 2025-10-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypublicapp', '0010_alter_site_company'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='section',
            name='section_site_id_3f8d01_idx',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='section',
            name='site',
        ),
    ]
