# Generated by Django 5.2.3 on 2025-10-16 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypublicapp', '0011_remove_section_section_site_id_3f8d01_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parentSection',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='mypublicapp.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='mainSection',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='mypublicapp.section'),
            preserve_default=False,
        ),
    ]
