# Generated by Django 5.2.3 on 2025-10-16 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'appEntity',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='AppEntityField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('order', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.appentity')),
            ],
            options={
                'db_table': 'appEntityField',
            },
        ),
        migrations.CreateModel(
            name='AppEntityOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('view', 'Consultar'), ('add', 'Añadir'), ('change', 'Modificar'), ('delete', 'Suprimir'), ('export', 'Exportar'), ('exec', 'Ejecutar')], default='view', max_length=10)),
                ('option', models.CharField(max_length=60, unique=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.appentity')),
            ],
            options={
                'db_table': 'appEntityOption',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=44)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
            ],
            options={
                'db_table': 'appSession',
            },
        ),
    ]
